Traceback (most recent call last):
  File "/Users/giuseppeciccone/OneDrive - University of Glasgow/PhD/Nanoindentation/Nanoindentation Github/nanoindentation/pynumdiff_test.py", line 108, in <module>
    params, val = pynumdiff.optimize.smooth_finite_difference.meandiff(y, dx, params=None,
  File "/opt/anaconda3/lib/python3.8/site-packages/pynumdiff/optimize/smooth_finite_difference/__smooth_finite_difference__.py", line 64, in meandiff
    opt_params, opt_val = __kerneldiff__(function, x, dt, params, options, dxdt_truth, tvgamma, padding, metric)
  File "/opt/anaconda3/lib/python3.8/site-packages/pynumdiff/optimize/smooth_finite_difference/__smooth_finite_difference__.py", line 39, in __kerneldiff__
    opt_params, opt_val = __optimize__(params, args)
  File "/opt/anaconda3/lib/python3.8/site-packages/pynumdiff/optimize/__optimize__.py", line 119, in __optimize__
    pool = Pool()
  File "/opt/anaconda3/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/anaconda3/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/opt/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/anaconda3/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
